name: CMake CI/CD (Build & Deploy)

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            path: build/Debug/asm-analyze.exe
            artifact-name: asm-analyze-win.exe

          - name: macOS
            os: macos-latest
            path: build/asm-analyze
            artifact-name: asm-analyze-macos

          - name: Linux
            os: ubuntu-latest
            path: build/asm-analyze
            artifact-name: asm-analyze-linux

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.artifact-name }}
          path: ${{ matrix.config.path }}

      - name: Create Release
#        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.0_${{ matrix.config.os }}
          name: v0.1.0 ${{ matrix.config.os }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.github.token }}

      - name: Upload Artifacts to Release
#        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.0_${{ matrix.config.os }}
          files: ./${{ matrix.config.path }}
