name: CMake CI/CD (Build & Deploy)

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            path: build\Debug\asm-analyze.exe
            artifact-name: asm-analyze-win.exe

          - name: macOS
            os: macos-latest
            path: build/asm-analyze
            artifact-name: asm-analyze-macos

          - name: Linux
            os: ubuntu-latest
            path: build/asm-analyze
            artifact-name: asm-analyze-linux

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.artifact-name }}
          path: ${{ matrix.config.path }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'  # Ensure this runs only on manual dispatch

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: asm-analyze-win.exe
          path: ./artifacts/win

      - name: Download Build Artifacts (macOS)
        uses: actions/download-artifact@v4
        with:
          name: asm-analyze-macos
          path: ./artifacts/macos

      - name: Download Build Artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: asm-analyze-linux
          path: ./artifacts/linux

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          release_name: Release v0.1.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.github.token }}

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          files: |
            ./artifacts/win/asm-analyze-win.exe
            ./artifacts/macos/asm-analyze-macos
            ./artifacts/linux/asm-analyze-linux
        env:
          GITHUB_TOKEN: ${{ secrets.github.token }}